name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --t assoc

  run:
    runs-on: ubuntu-latest
    steps:
    - run: docker run assoc >> output.txt
    - uses: actions/upload-artifact@v4
      with:
        name: banking-output
        path: output.txt
