name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t banking

  generate:
  
    runs-on: ubuntu-latest
    
    steps:
    - run: mkdir -p path/to/artifact
    - run: docker run banking >> output.txt
    - uses: actions/upload-artifact@v4
      with:
        name: banking
        path: output.txt
    
